{{- if .Values.ingress.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Must be a valid DNS name:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
spec:
    rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
            - path: "{{ .Values.ingress.path }}"
              pathType: Prefix
              backend:
                service:
                  name: "{{ .Values.resourceName }}"
                  port:
                    number: {{ .Values.port }}
{{- end -}}
