{{- $port := .Values.port }}
{{- $resourceName := .Values.resourceName }}
{{- if or .Values.ingress_host .Values.ingress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Must be a valid DNS name:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # Makes the middleware that redirects www to non-www apply to this Ingress
    traefik.ingress.kubernetes.io/router.middlewares: traefik-redirect-www-to-non-www@kubernetescrd
spec:
    rules:
    {{- if .Values.ingress_host }}
    - host: "{{ .Values.ingress_host }}"
      http:
        paths:
            - path: "{{ .Values.ingress_path }}"
              pathType: Prefix
              backend:
                service:
                  name: "{{ .Values.resourceName }}"
                  port:
                    number: {{ .Values.port }}
    - host: "www.{{ .Values.ingress_host }}"
      http:
        paths:
            - path: "{{ .Values.ingress_path }}"
              pathType: Prefix
              backend:
                service:
                  name: "{{ .Values.resourceName }}"
                  port:
                    number: {{ .Values.port }}
    {{- end }}
    {{- range $ingress := .Values.ingress }}
    - host: {{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path | default "/"  }}
            pathType: Prefix
            backend:
              service:
                name: "{{ $resourceName }}"
                port:
                  number: {{ $port }}
    - host: www.{{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path | default "/"  }}
            pathType: Prefix
            backend:
              service:
                name: "{{ $resourceName }}"
                port:
                  number: {{ $port }}
    {{- end }}
{{- end -}}
