---
# Container image ref for cron job
image:

# Container image tag for cron job
tag:

# Possibility to override default imagePullPolicy
imagePullPolicy:

# Annotations to put on the CronJob:
cronJobAnnotations: []

# Default Spring Profile:
springProfiles: "kubernetes"

# Example:  */1 * * * *
schedule:

# Max lifetime of the pod:
activeDeadlineSeconds:

# It is possible to use a normal yaml tree here, for example:
# root:
#   node1: 1
#   node2: 2
#
# If there is a lot of config, it is useful to use the helm function --set-file.
config:

# Reference secrets that are mounted on the pod:
secretRefs: []

# Reference configMaps that are mounted on the pod:
configMapRefs: []

memory_request: "256Mi"
memory_limit: "1024Mi"

cpu_request: "100m"
cpu_limit: "2.5"

# If this is enabled, a docker image with a mssql database is created.
# The following env variables are then added to the pod:
# DATABASE_CONTAINER_USER, DATABASE_CONTAINER_PASSWORD, DATABASE_CONTAINER_HOST_AND_PORT and DATABASE_CONTAINER_DATABASE
database_container_enabled: false
database_container_image: "dsbacr.azurecr.io/dsb-norge/dsb-mssql-server:2019-latest"
# This is hardcoded in the image used:
database_container_password: DoN0tUse1Production
