{{ if .Values.job_secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cron-secret
  namespace: {{ .Release.Namespace }}
data:
{{ template "envifyB64" (list "" .Values.job_secrets) }}
{{ end }}