{{ if .Values.database_container.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-database-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-db-app"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-db-app"
      annotations:
        # We change this annotation on change in chart or parameters, to force re-create of pods (to pick up config changes etc)
        # We create a string based on the chart version, and the resolved configuration values.
        # See https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
        checksum: "chart-version={{ .Chart.Version }}_config-hash={{ .Values | toString | sha256sum }}"
    spec:
      hostname: "{{ .Release.Name }}-db-svc"
      containers:
        - name: "{{ .Release.Name }}-database-container"
          image: "{{ .Values.database_container.image }}"
          resources:
            requests:
              memory: "1024Mi"
              cpu: "0.2"
            limits:
              memory: "2048Mi"
              cpu: "2.5"
          env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: {{ .Values.database_container.password | quote }}
          - name: MSSQL_SA_PASSWORD
            value: {{ .Values.database_container.password | quote }}
          ports:
          - containerPort: 1433
{{ end }}
