{{- range $role := .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}-{{ $role }}-binding
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-app
subjects:
  - kind: ServiceAccount
    name: {{ $.Release.Name }}-service-account
roleRef:
  kind: Role
  name: {{ $role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
