apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-service
    spring-boot: "true"
    chart-name: "{{ .Chart.Name }}"
    chart-version: "{{ .Chart.Version }}"
    # Picked up by Spring Boot Admin:
    # https://codecentric.github.io/spring-boot-admin/current/#_converting_serviceinstances
    management.port: "{{ .Values.application_actuator_port }}"
    app.kubernetes.io/name: {{ .Values.dashboard.name | default .Release.Name }}
    app.kubernetes.io/version: {{ .Values.tag }}
    app.kubernetes.io/component: {{ .Values.dashboard.component | default "API" }}
    app.kubernetes.io/part-of: {{ .Values.dashboard.partOf | default .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: web
      port: {{ .Values.application_web_port }}
    - name: actuator
      port: {{ .Values.application_actuator_port }}
  selector:
    app: {{ .Release.Name }}-app
