name: 'Verify PR'

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Workspace cleanup
        run: rm -rf ${{ github.workspace }} && mkdir ${{ github.workspace }}

      - name: Checkout working branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.6.3

      - name: Run linting
        run: helm lint charts/*

      - name: Run Helm Unittests
        run: docker run --rm --name unittest --volume "$(pwd)":/apps quintush/helm-unittest --helm3 charts/*

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: kind-cluster-config.yaml
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}

      - name: Load custom test application image
        run: |
          az acr login --name dsbacr --username ${{ secrets.AZ_CR_USER }} --password ${{ secrets.AZ_CR_SECRET }}
          docker pull dsbacr.azurecr.io/dsb-norge/test-application:2021.06.03.69273
          kind load --name chart-testing docker-image dsbacr.azurecr.io/dsb-norge/test-application:2021.06.03.69273

      - name: Run chart-testing (install)
        run: ct install --all
