name: 'Verify PR'

on:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Workspace cleanup
        run: rm -rf ${{ github.workspace }} && mkdir ${{ github.workspace }}

      - name: Checkout working branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.3

      - name: Run linting (helm)
        run: helm lint charts/*

      - name: Run Helm Unittests
        run: docker run --rm --name unittest --volume "$(pwd)":/apps helmunittest/helm-unittest charts/*

      - name: log into azure container registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: dsbacr.azurecr.io
          username: ${{ vars.ORG_AZURE_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.ORG_AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run linting (ct)
        run: ct lint --all --validate-maintainers=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0
        with:
          config: kind-cluster-config.yaml
        env:
          GITHUB_WORKSPACE: ${{ env.GITHUB_WORKSPACE }}

      - name: Load custom test application image
        run: |
          # Make image(s) available to kind cluster as it has no pullSecrets
          # K8s defaults to always pull if tag is "latest", this is prevented by having
          # 'imagePullPolicy: "Never"' in charts/*/ci/*-values.yaml
          docker pull dsbacr.azurecr.io/dsb-norge/test-application:latest
          kind load --name chart-testing docker-image dsbacr.azurecr.io/dsb-norge/test-application:latest

      - name: Run chart-testing (install)
        run: ct install --all
